name: 04 - Using Actions

on: push

jobs:
   build:
         runs-on: ubuntu-latest
         #check out the code from repository
         steps:
           - name: Checkout Code
             run: actions/checkout@v4
           - name: Printing folders
             run: ls
             

