name: 05 - 1 - Filter Activity Types

on: 
    pull_request:
        types:
           - closed
        branches:
           - main
 
jobs:
    echo:
      runs-on: ubuntu-latest
      
      steps:
         - name: Activity Type
           run: echo "Running whenever pull request is opned or synchronize and base branch is main." 