name: 06 - Contexts
#Using inputs contexts
run-name: 06 - Contexts | DEBUG - ${{inputs.DEBUG}}

on: 
        push:
        workflow_dispatch:
            #Define Input contexts how to get use in workflow
             inputs:
                debug:
                    type: boolean
                    default: false
            

jobs:           
        echo_contexts:
             runs-on: ubuntu-latest
             #Define env type of contexts
             env: 
               MY_JOB_VAR: 'job'
               MY_OVERWRITTEN_VAR: 'job'
             
             steps:
               - name: Display information
                 #Using github contexts
                 run: |
                   echo "Event Name: ${{github.event_name}}" 
                   echo "Ref: ${{github.ref}}"
                   echo "SHA: ${{github.sha}}"
                   echo "Actor: ${{github.workflow}}"
                   echo "Workflow: ${{github.actor}}"
                   echo "Run ID: ${{github.run_id}}"
                   echo "Run number: ${{github.run_number}}"
                
               - name: Retrieve Variable
                 #using var contexts
                 run: |
                   echo "Variable name ; ${{vars.MY_VAR}}"
                
               - name: Print Env Variable 1
                #overwriting env context inside steps
                 env:
                   MY_OVERWRITTEN_VAR: 'steps'
                #using env contexts   
                 run: |
                   echo "Workflow env: ${{env.MY_JOB_VAR}}"
                   echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"
                 
               - name: Print Env Variable 2
               #using env contexts  
                 run: |
                   echo "Workflow env: ${{env.MY_JOB_VAR}}"
                   echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"   